data:
  batch_size: 128
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: imagenet100_local
  num_workers: 16
  pin_mem: true
  root_path: /content
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
  with_index: true
daw:
  ema_alpha: 0.7
  enabled: true
  gamma: 0.3
  mode: ema
  w_max: 1.2
  w_min: 0.8
  warmup_epochs: 10
logging:
  folder: auto
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 16
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_small
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 100
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 10
  weight_decay: 0.04
